// Auto-generated by openapi-typescript — run `pnpm generate:api` to regenerate
// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface paths {}
// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface components {}
